# Manipulating arrays

## $ \S 1 $ Basic operations on vectors

We saw in the previous notebook that a vector such as $ (1, 2, 3) $
can be represented in NumPy as a $ 1D $ array:

In [1]:
import numpy as np

v = np.array([1, 2, 3])
w = np.array([4, 5, 6])

We can also use NumPy to conveniently perform all of the vector operations
that we learned in Linear Algebra.

Given vectors $ \mathbf v = (v_1, v_2, \cdots, v_n) $ and $ \mathbf w = (w_1,
w_2, \cdots, w_n) $ with the same number $ n $ of coordinates, their __sum__ and
__difference__ $ \mathbf v \pm \mathbf w $ are computed element-wise:
$$
\mathbf v \pm \mathbf w = (v_1 \pm w_1,\,v_2 \pm w_2,\, \cdots,\, v_n \pm w_n)\,.
$$
NumPy uses the same notation:

In [17]:
s = v + w
print(s, type(s))

d = v - w
print(d, type(d))

[5 7 9] <class 'numpy.ndarray'>
[-3 -3 -3] <class 'numpy.ndarray'>


__Scalar multiplication__ of a vector by a factor $ c \in \mathbb{R} $ is also defined
element-wise:
$$
c\, \mathbf v = (c\,v_1, c\,v_2, \cdots, c\,v_n)\,.
$$

In [19]:
print(2 * v)
print(-3.14 * v)
print(0 * v)

[2 4 6]
[-3.14 -6.28 -9.42]
[0 0 0]


Naturally, we may also write $ -\mathbf v $ instead of $ (-1)\mathbf v $. Try it in the code cell below:

If we operate on an array whose datatype is `int` and any floating-number is
involved in the operation, then the result will be of type `float`.  A similar
observation applies to any other type coercion.

In [4]:
# `v.dtype`` yields the datatype of the elements of v.
# We will study `dtype` in more detail later.
v = np.array([1, 2, 3])
print(v, v.dtype)

u = 1.0 * v
print(u, u.dtype)

s = v + (True, False, True)
print(s, s.dtype)

[1 2 3] int64
[1. 2. 3.] float64
[2 2 4] int64


__Exercise:__ Can you explain the output of the following cell?

In [13]:
x = np.array([-1, 0, 1, 3])
b = np.array([True, False, True, False])

x_plus_b = x + b
print(x_plus_b, x_plus_b.dtype)


[0 0 2 3] int64


The __dot product__ $ \mathbf v \cdot \mathbf w $ of two vectors $ \mathbf v =
(w_1, w_2, \cdots, w_n) $ and $ \mathbf w  = (w_1, w_2, \cdots, w_n) $ of the
same shape is the sum of the products of their corresponding elements:
$$
\mathbf v \cdot \mathbf w = v_1w_1 + v_2w_2 + \cdots + v_nw_n \,.
$$

In [14]:
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])
dot_product = np.dot(v, w)
print(dot_product)

32


Equivalently, we can also use the `@` operator to compute dot products:

In [16]:
alternative_dot_product = v @ w
print(alternative_dot_product)

32


The dot product is symmetric (i.e., $ \mathbf v \cdot \mathbf w = \mathbf
w \cdot \mathbf v) $ and bilinear, meaning that:
$$ (a\, \mathbf u + b\,\mathbf v) \cdot \mathbf w
= a\, (\mathbf u \cdot \mathbf w) + b\, (\mathbf v \cdot \mathbf w) $$
for any three vectors $ \mathbf u,\, \mathbf v,\, \mathbf w $ and scalars $ a $
and $ b $. Actually the preceding equation only states linearity in the first
component, but linearity in the second component follows from the symmetry.
These properties are immediate consequences of the definition.

The __norm__ or __length__ of a vector
$ \mathbf v = (v_1, v_2, \cdots, v_n) \in \mathbb R^n $ is defined by
$$ \Vert \mathbf v \Vert = \sqrt{\mathbf v \cdot \mathbf v} = \sqrt{v_1^2 + v_2^2 + \cdots v_n^2}\,. $$
In NumPy, it can be computed as follows:

In [ ]:
v = np.array([0, 3, -4])

print(np.linalg.norm(v))  # Using the function `norm` from the `linalg` submodule
print(np.sqrt(np.dot(v, v)))  # Taking the square root of the dot product

5.0
5.0


Recall that two vectors are _orthogonal_ (or _perpendicular_) if and only if their dot product vanishes.
As an example, try to decide whether the two vectors below are orthogonal using Python:

In [19]:
a = np.array([-3, 4, 7, 3, -6])
b = np.array([2, 5, -2, 4, 2])

More generally, recall from Linear Algebra the following relationship between the dot product and
the angle $ \theta \in [0, \pi] $ between two vectors:
$$
\mathbf v \cdot \mathbf w = \Vert \mathbf v \Vert \,\Vert \mathbf w \Vert \cos \theta\,.
$$
                                                                                                    

__Exercise:__ Consider the three vectors $ \mathbf a $, $ \mathbf b $ and $ \mathbf c $ in the code cell below.

(a) Compute $ \mathbf d = 3\mathbf a + 2\mathbf b - \mathbf c $.

(b) Project $ \mathbf d $ onto $ \mathbf b $ to get $ \mathbf e $. That is, compute 
$$ \mathbf e = \frac{\mathbf d \cdot \mathbf b}{\mathbf b \cdot \mathbf b} \mathbf b \,.$$

(c) Scale $ \mathbf e $ by $ 2 $ to get $ \mathbf f $.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

__Exercise:__ Compute the angle between the vectors $ \mathbf v = (3, 3) $ and $ (0, 2) $. _Hint:_ Use
`np.arccos` to compute the arccosine and `np.degrees` to transform the result to degrees.


__Exercise:__ The __canonical basis__ in $ \mathbb R^3 $ consists of the three vectors
$$ \mathbf e_1 = (1, 0, 0)\,, \quad \mathbf e_2 = (0, 1, 0)\,, \quad \text{and} \quad \mathbf e_3 = (0, 0, 1)\,. $$
Compute and print all possible dot products $ \mathbf e_i \cdot \mathbf e_j $. What is the
norm of $ \mathbf e_i $? What is the angle between $ \mathbf e_i $ and $ \mathbf e_j $?
_Hint:_ Don't do this manually; store the vectors in a list and use for loops.

The __cross product__ $ \mathbf v \times \mathbf w \in \mathbb R^3 $ of two vectors in
three-dimensional space results in a vector orthogonal to both $ \mathbf v $ and $ \mathbf w $
whose length is given by 
$$
\Vert{\mathbf v \times \mathbf w}\Vert = \Vert{\mathbf v}\Vert\,\Vert{\mathbf w}\Vert\,\sin \theta\,,
$$
where again $ \theta \in [0, \pi] $ denotes the angle between $ \mathbf v $ and
$ \mathbf w $. The cross product is uniquely determined by these two properties
together with the fact that the basis $ \big(\mathbf v,\, \mathbf w,\, \mathbf v
\times \mathbf w \big) $ is _positively oriented_ (i.e., this trio of vectors,
in this order, satisfies the "right-hand rule"). Like the dot product, the cross
product $ \times $ is also bilinear, but it is antisymmetric instead of
symmetric:
$$ \mathbf w \times \mathbf v = -\mathbf v \times \mathbf w \quad (\mathbf v,\, \mathbf w \in \mathbb R^3)\,.
$$

__Exercise:__ Compute all possible cross products of the canonical basis vectors $ \mathbf e_i $ in $ \mathbb R^3 $
using the function `cross`. _Hint:_ Use for loops.

In [32]:
e1 = np.array([1, 0, 0])
e2 = np.array([0, 1, 0])
cross_product = np.cross(e1, e2)
print(cross_product)

[0 0 1]


A __unit vector__ is a vector of length $ 1 $. To get a unit vector $ \mathbf u $ having the same
direction as a given nonzero vector $ \mathbf v $, we can simply divide the latter by its norm:
$$
\mathbf u = \frac{\mathbf v}{\Vert \mathbf v \Vert}\,.
$$

__Exercise:__ How many unit vectors in $ \mathbb{R}^3 $ are parallel to $ \mathbf v = (3, -4, 10) $? Compute all of them using NumPy.

In [23]:
v = np.array([3, -4, 12])

## $ \S 2 $ Basic operations involving matrices

We can __add__ and __subtract__ two matrices (or more generally any two arrays of the
same number of dimensions and shape) using simply `+` and `-` respectively:

In [24]:
A = np.array([[1, 2, 3],
              [1, 2, 3]])

B = np.array([[4, 4, 4],
              [5, 5, 5]])

print("Matrix A:\n", A, '\n')
print("Matrix B:\n", B, '\n')
print("Sum:\n", A + B, '\n')
print("Difference:\n", A - B, '\n')

Matrix A:
 [[1 2 3]
 [1 2 3]] 

Matrix B:
 [[4 4 4]
 [5 5 5]] 

Sum:
 [[5 6 7]
 [6 7 8]] 

Difference:
 [[-3 -2 -1]
 [-4 -3 -2]] 



Similarly, to __scale__ every element of a matrix (or, more generally, $ n
$-dimensional array) $ A $ by a scalar $ c $, we may use either `c * A` or `A * c`:

In [12]:
c = 2
print("c * A:\n", c * A, '\n')
print("A * c:\n", A * c, '\n')

c * A:
 [[2 4 6]
 [2 4 6]] 

A * c:
 [[2 4 6]
 [2 4 6]] 



For __multiplication__ of 2D arrays, i.e., matrices, NumPy uses the `np.matmul` function or
the `@` operator. Note that we are referring here to matrix multiplication,
which is different from element-wise multiplication. In particular, the number
of columns in the first matrix must match the number of rows in the second
matrix: The product of an $ m \times n $ matrix by an $ n \times p $ matrix has shape $ m \times p $.

In [17]:
# Creating a 2 x 3 matrix A:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Creating a 3 x 4 matrix B:
B = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14],
              [15, 16, 17, 18]])

# Multiplying A and B:
C = np.matmul(A, B)
D = A @ B
print(C, C.shape)
print(D, D.shape)

[[ 74  80  86  92]
 [173 188 203 218]] (2, 4)
[[ 74  80  86  92]
 [173 188 203 218]] (2, 4)


📝 `np.matmul` and `@` are completely equivalent in their output and
performance. The choice between them is usually a matter of preference and code
readability.

__Exercise:__ Compute `C * C`, `C**2` and `C**(-1)` for the matrix $ C $ below. Can you explain these results? We will return to these operations in a later section.

In [40]:
C = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

To instantiate a copy of the identity matrix of shape $ n \times n $,
we can use the function `np.identity` as follows:

In [26]:
n = 4
I = np.identity(n)  # Create an n x n identity matrix
print(I)
print(I.dtype)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
float64


A more flexible version of `np.identity` allowing the creation of non-square matrices is `np.eye`:

In [27]:
E = np.eye(3, 4)
print(E)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


The third (optional) parameter of `np.eye` specifies an offset to the diagonal:

In [31]:
I = np.eye(4, 4, 0)   # An offset of 0 corresponds to the main diagonal
U = np.eye(4, 4, 1)   # An offset of 1 corresponds to the diagonal immediately above the main one
L = np.eye(4, 4, -2)  # A negative offset to refers to a lower diagonal

print(I, '\n')
print(U, '\n')
print(L, '\n')

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]] 



__Exercise:__ Compute the linear combination $ M^2 - 3 M + 2I $, for $ M $ the matrix below:

In [36]:
M = np.array([[ 0, -2],
              [ 1,  3]])

When multiplying a 2D array (matrix) by a 1D array (vector), _the vector is
temporarily viewed as a column matrix and the operation is then treated as a
matrix multiplication_. Thus, matrix-vector multiplication can also be handled
by `@`, or equivalently `np.matmul`:

In [32]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
v = np.array([-1, 0, 1])

prod1 = A @ v
prod2 = np.matmul(A, v)
print(prod1, prod1.shape)
print(prod2, prod2.shape)

[2 2] (2,)
[2 2] (2,)


To compute the __determinant__ and the __inverse__ of a _square_ matrix, we can use the `np.linalg.det` and the `np.linalg.inv` functions, respectively:

In [42]:
X = np.array([[1, 2],
              [3, 4]])
print("Matrix X:\n", X)
print("Determinant of X:", np.linalg.det(X))

Matrix X:
 [[1 2]
 [3 4]]
Determinant of X: -2.0000000000000004


In [27]:
A = np.array([[0, 1],
              [-1, 0]])
A_inverse = np.linalg.inv(A)
print("Inverse of A:\n", A_inverse)
print("Product of A and its inverse:\n", A @ A_inverse)

Inverse of A:
 [[-0. -1.]
 [ 1.  0.]]
Product of A and its inverse:
 [[1. 0.]
 [0. 1.]]


__Exercise:__ Find the area of a parallelogram spanned by vectors 
$ (3, 5) $ and $ (2, 4) $ in $ \mathbb{R}^2 $.  Recall that this area can be
computed as the absolute value of the determinant of the matrix formed by these
vectors. _Hint:_ The absolute value function in NumPy is denoted by `np.abs`.

__Exercise:__ Given two square matrices $ C $ and $ D $ of the same size, recall
that the determinant of their product is the product of their determinants:
$$
\det(CD) = \det(C) \cdot \det(D)
$$
Verify this identity in the particular example where
$$
C = \begin{bmatrix}
1 & 2 \\
3 & 4 \\
\end{bmatrix} \quad \text{and} \quad
D = \begin{bmatrix}
-1 & 1 \\
1 & -1 \\
\end{bmatrix}\,.
$$

__Exercise:__ Solve the linear system of equations given by $ A\mathbf{x} = \mathbf{b} $, where
$$
A = \begin{bmatrix}
1 & 2 & 3 \\
0 & 1 & 4 \\
5 & 6 & 0 \\
\end{bmatrix},
\mathbf b = \begin{bmatrix}
3 \\
7 \\
8 \\
\end{bmatrix}
$$
Verify your answer by multiplying $ A $ by $ \mathbf x $.
_Hint:_ Use the inverse of $ A $ to find $ \mathbf{x} = A^{-1}\mathbf{b} $.

__Exercise (simple cryptographic encoding/decoding):__
In this exercise we will use matrix multiplication to encode a simple message
and then decode it using the inverse of the encoding matrix.

Assign a numerical value to each letter of the alphabet (e.g., whitespace
$ = 0 $, $ A =1 $, $ B =2,\cdots $, $ Z = 26 $) and choose a
word or short message to encode.  Represent the message as a $ 2 \times n $
matrix, where each entry corresponds to a letter. For example, "PYTHON" would be
represented as
$$
\begin{bmatrix}
P & T & O \\
Y & H & N
\end{bmatrix}
=
\begin{bmatrix}
16 & 20 & 15 \\
25 & 8 & 14
\end{bmatrix}
$$
Corresponding utilities have already been provided below through the functions
`text_to_ints` and `int_to_text`.

Now create a $ 2 \times 2 $ encoding matrix $ A $ and ensure it is invertible.
Encode the message by multiplying it with the encoding matrix.  Decode the
message by multiplying the encoded matrix by the inverse of the encoding matrix.
Verify that the decoded message matches the original message.

In [33]:
def text_to_ints(text):
    """Convert a text message to a 2D array of integers suitable for encoding, with spaces encoded as 0.
    Ensures the letters go in sequence along the first column, then along the second column, etc., for a 2xN array."""
    # Convert to uppercase
    text = text.upper()
    # Convert characters to integers (' ' to 0, A=1, B=2, ..., Z=26)
    ints = np.array([0 if char == ' ' else ord(char) - ord('A') + 1 for char in text])
    # Pad with 0 (space) to ensure the total number of elements is divisible by 2
    while len(ints) % 2 != 0:
        ints = np.append(ints, 0)  # Pad with 'space' represented as 0
    
    # Reshape into 2 x N, filling the array column-wise
    return np.reshape(ints, (2, -1), order='F')

def int_to_text(ints):
    """Convert a 2D array of integers back to a text message, with 0 decoded as space.
    Expects input shape to be 2 x n."""
    decoded_message = ''
    # Iterate over the array assuming a shape of 2 x n:
    for row in range(ints.shape[1]):  # Iterate columns based on the corrected shape
        for col in range(ints.shape[0]):
            value = ints[col, row]
            # Convert each integer back to a character, translating 0 back to space
            if value == 0:
                decoded_message += ' '  # Convert 0 back to space
            else:
                decoded_message += chr(int(value) + ord('A') - 1)
    return decoded_message.strip()  # Strip trailing spaces if any

ints = text_to_ints("Python")
print(ints)
int_to_text(ints)

[[16 20 15]
 [25  8 14]]


'PYTHON'

## $ \S 3 $ Attributes of arrays

Recall from the previous notebook that, just as in Linear Algebra, an important
property of a $ 2D $ array is its **shape**, which is the element count
along each of its **axes** (vertical and horizontal).
Referring to the example below, the shape of our matrix $ A $ is
$ (3, 4) $, or $ 3 \times 4 $, since it has three rows and four columns:

In [3]:
import numpy as np

A = np.array([[1., 2., 3., 4.],
              [1., 4., 9., 16.],
              [1., 8., 27., 64.]])
print(A)

[[ 1.  2.  3.  4.]
 [ 1.  4.  9. 16.]
 [ 1.  8. 27. 64.]]


The number of dimensions and shape of an arbitrary array are stored in its `ndim` and `shape` attributes, respectively:

In [39]:
print(A.ndim)    # Print the number of dimensions of A
print(A.shape)   # Print the shape of A

2
(3, 4)


The number of dimensions of an array is a positive integer, while its shape is always a tuple, even when the array is one-dimensional:

In [ ]:
a = np.array([11, 13, 17])
print(a.shape, "<-- Note that the shape is not '3', but rather the tuple '(3, )'")
print(type(a.shape))

(3,) <-- Note that the shape is not '3', but rather the tuple '(3, )'
<class 'tuple'>


__Exercise:__ What are the dimension and shape of an empty array?

An instance of a specific class, such as the array $ A $ of type `ndarray`,
is equipped with a set of predefined **attributes**. Attributes are simply
_properties inherent to every instance of the class_ (in this case, that of
ndarrays) _and which together describe the state of that instance_. 

📝 To access an attribute of an object `x`, the syntax is `x.<attribute>`.

For example, suppose that we want to design a Python class to represent cars.
An instance of this class would then be a representation of one specific car
in the real world.  Some plausible attributes of this class could be:
* Its color (say, `color`, of type `str`).
* The year in which it was manufactured (say, `year`, of type `int`).
* Whether it is electric or not (say, `electric`, of type `boolean`).
* The fuel efficiency of the car (say, `kilometers_per_liter`, of type `float`).

And so on for any other relevant property of cars that we might want to include
in our model. Note that the values of these attributes for different car
instances will vary, in general.

Although ndarrays come with several attributes, most of them relate to the array's
internal representation or low-level utilities. The five most frequently used and
conceptually important attributes of ndarrays are:
* `ndim`: The number of dimensions (axes) of the array.
* `shape`: Indicates how many elements lie along each axis.
* `size`: The total number of elements in the array.
* `dtype`: The data type of the elements of the array.
* `T`: The transpose of the array.

__Exercise:__ Print the number of dimensions, shape, size, datatype and transpose of the following array. Is the datatype what you expected? Explain.

In [5]:
E = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9.]])

__Exercise:__ If an array has shape $ (2, 3, 4) $, what is its size? More generally, what is the size of an array of shape $ (n_1, n_2, \cdots, n_d) $? What is the type of the object returned by `size`?

__Exercise:__ Let
$$
B = \begin{bmatrix}
1 & 2 & 3 \\
-4 & -5 & -6 \\
\end{bmatrix}\,.
$$
Use NumPy to create this array and compute its dimension, shape, size, datatype and transpose.
Can you build an array whose datatype is `bool`?

__Exercise:__ A _square matrix_ has the same number of rows and columns. Write a
function `is_square(matrix)` that accepts a 2D array as its argument and returns
`True` or `False` depending on whether the given matrix is square or not. How
would you generalize to multidimensional arrays?

__Exercise:__ Write a function to determine whether a given matrix $ A $ is
symmetric (i.e., whether $ A^T = A $). _Hint:_ When applied to two arrays of
the same shape, the `=` operator performs an element-wise comparison and
returns a Boolean array of the same shape. Use `np.array_equal(A, B)` to
check if two arrays $ A $ and $ B $ have the same shape and elements.

In [46]:
a = np.array([1, 2])
b = np.array([1, 2])
a == b

array([ True,  True])

__Exercise:__ What is the transpose of a $ 1D $ array? What about $ 3D $ arrays? In general, how is the transpose
of an $ n $-dimensional array defined?

## $ \S 4 $ Array methods

Besides attributes, objects of a certain class usually come with predefined
**methods**. _Methods are functions associated to each instance of that class that
have direct access to that intance's state_. The
syntax for calling method `f` of object `x` is `x.f(<arguments>)`. For instance,
the `sum` method associated to each array returns the sum of all of its entries:

In [ ]:
C = np.array([[-1.0, 2.3, 3.7],
              [-4.5, 2.7, -0.7]])
print(C.sum())

2.5


As an optional argument to `sum`, we can designate an axis over which the sum should take place. As always in Python, indexing is zero-based, meaning that for matrix $ C $ above, the rows lie along axis $ 0 $ and the columns along axis $ 1 $.

In [ ]:
print(C.sum(axis=0))

[-5.5  5.   3.2]


If we think of $ C $ as the matrix $ C = (c_{ij}) $, where $ i $ is the index
for axis $ 0 $ (i.e., the index of rows), then taking the sum along this axis
means that for each $ j $, NumPy computes $ \sum_{i} c_{ij} $, resulting in the
preceding vector since $ C $ has three columns. To put it another way, the axis
specified as the argument to `sum` is the one that gets collapsed, in this case
by the summation.

__Exercise:__ Compute the sum of the entries of $ C $ along the column index.

The main array methods that involve mathematical operations are:

| Method    | Description                                          |
|-----------|------------------------------------------------------|
| `sum`     | Returns the sum of all the elements in the array.   |
| `prod`    | Returns the product of all the elements in the array.|
| `mean`    | Returns the arithmetic mean of the array.           |
| `std`     | Returns the standard deviation of the array.        |
| `var`     | Returns the variance of the array.                  |
| `min`     | Returns the minimum value of the array.             |
| `max`     | Returns the maximum value of the array.             |
| `argmin`  | Returns the indices of the minimum value along an axis. |
| `argmax`  | Returns the indices of the maximum value along an axis. |
| `cumsum`  | Returns the cumulative sum of the elements along a given axis. |
| `cumprod` | Returns the cumulative product of the elements along a given axis. |


_All of these can be applied to a specific axis or axes by setting a value for
the `axis` parameter_. One can also apply them to more complex subarrays using
slices.

In [44]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Maximum of each row, i.e., along axis 1:
max_rows = arr.max(axis=1)
print(max_rows)

# Mean (average) of each column, i.e., along axis 0:
mean_cols = arr.mean(axis=0)
print(mean_cols)

# Standard deviation of each row, i.e., along axis 1:
std_rows = arr.std(axis=1)
print(std_rows)

[3 6 9]
[4. 5. 6.]
[0.81649658 0.81649658 0.81649658]


## $ \S 5 $ Reshaping arrays

Reshaping arrays is a common and fundamental operation in NumPy. There is both
a function and a method named `reshape` that can accomplish this:

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a, end='\n\n')

A = np.reshape(a, (3, 2))  # Here we use the _function_ `reshape`
B = a.reshape((2, 3))   # Here we use the `reshape` _method_

print(A, end='\n\n')  # Here a has been reshaped into a 3 by 2 matrix
print(B, end='\n\n')  # Here a has been reshaped into a 2 by 3 matrix


[1 2 3 4 5 6]

[[1 2]
 [3 4]
 [5 6]]

[[1 2 3]
 [4 5 6]]



Note that when reshaping an array, the new shape must be compatible with the
size of the original array. For example, the following results in an error:

In [ ]:
C = np.reshape(a, (2, 2))

When reshaping an array, we may also specify $ -1 $ in a dimension to instruct
NumPy to infer the number of elements along that dimension from the size of the
array and that of the remaining dimensions. This is especially useful when an
array is passed to us by the user as an argument in a function call, but we do
not know in advance how many entries it has:

In [ ]:
a = np.array([[1, 2],
              [3, 4]])
A = a.reshape((-1, 1))  # Reshape into a column vector
print(A)

[[1]
 [2]
 [3]
 [4]]


In this example we wanted to reshape our array so that the result would have
one column, but didn't want to figure out how many rows it should have for that
to happen. Here's another example, in which we reshape a $ 1D $ array into a
matrix and then to a row vector:

In [ ]:
x = np.arange(1, 13)
X = x.reshape((3, -1))
x_row = X.reshape((1, -1))

print(x, end='\n\n')
print(X, end='\n\n')
print(x_row, end='\n\n')

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]



📝 There is no essential difference between the function and the method versions
of `reshape`. In both cases, NumPy returns a _new_ array, while the original
array remains unchanged. However, these operations provide a view of the
original array's data whenever possible, meaning that they do not copy the
array's data unless necessary. Thus, _modifications to the data in the reshaped
array can affect the original array and vice versa_. Let's use the previous
example to illustrate this:

In [ ]:
X[0, 0] = -23  # Modify the top left element of X
print(x)  # The 0th element of x has also been affected!

[-23   2   3   4   5   6   7   8   9  10  11  12]


To create an independent copy of a NumPy array, we can use the `copy` method.
This method generates a new array object with the same data as the original
array, but stored in a separate memory location.

In [49]:
y = np.arange(3)  # y is the 1D array with entries 0, 1, 2
Y = y.copy().reshape((1, -1))  # Reshape y into an independent 2D row vector
y[0] = 10  # Modify 0th element of y
print(y)
print(Y)  # The 0th element of Y is not affected, since Y is an independent copy

[10  1  2]
[[0 1 2]]


📝 There is also a _function_ `np.copy` that is essentially equivalent to the method having the same name.

The `flatten` method takes a multi-dimensional array and returns a new,
independent _one-dimensional_ array containing all of the elements of the original
array, while preserving their order. 

In [ ]:
A = np.array([[1, 2],
              [3, 4]])
a = A.flatten()
print(a)

[1 2 3 4]


The order in which the elements are placed in the flattened array is based on
the lexicographic ordering of their indices in the original array. For example,
if we are dealing with a $ 3D $ array, then the entry at position $ (0, 0, 2) $
comes before the entry at $ (0, 1, 0) $, which will be placed before the entry
at $ (1, 0, 0) $.

In [ ]:
A = np.arange(6).reshape((2, 3))
print(A)
a = A.flatten()
print(a)

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
