# Introduction to NumPy

**NumPy**, which stands for _Numerical Python_, is a foundational package
for scientific computing in Python. It is almost universally imported with the
`np` alias, as follows:

In [2]:
import numpy as np

The central feature in NumPy is a new data structure called an **ndarray**
(an abbreviation of $n$-dimensional array), or simply **array**. An ndarray is a
grid of values of the same type, usually numerical.  For example, a $ 1 $-dimensional
array is essentially a vector in the sense of Linear Algebra. It can be
instantiated with the `array` function.

In [7]:
v = np.array([1, 2, 3])
print(v)
print(type(v))

[1 2 3]
<class 'numpy.ndarray'>


The number of dimensions of an array is also called its **rank**. A $ 2 $-dimensional
array, or array of rank $ 2 $, is just a matrix.

In [9]:
A = np.array([[1, 1, 1, 1],  # first row of matrix A
              [2, 2, 2, 2],  # second row
              [3, 3, 3, 3]]  # third row
             )
print(A)
print(type(A))

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]
<class 'numpy.ndarray'>


Note the use of _double_ brackets here: the first opening bracket `[` serves
to delimit the array, while the second one is being used to delimit the elements
of the first row. The rows are separated by commas, as are the elements within each row.

Just as in Linear Algebra, a $ 2D $ array can have any **shape**, which is the
number of elements along each of its **axes** (horizontal and vertical).
Referring to the preceding example, the shape of our matrix $ A $ is $ 3 \times 4 $,
or $ (3, 4) $, since it has three rows and four columns:

In [14]:
print(A.ndim)    # Print the number of dimensions of A
print(A.shape)   # Print the shape of A

2
(3, 4)


__Exercise:__ How would you create the matrix
$$
B = \begin{equation*}
\left[ \begin{array}{cc}
b_{11} & b_{12} \\
b_{21} & b_{22} \\
b_{31} & b_{32} \\
b_{41} & b_{42}
\end{array} \right]
\end{equation*}
$$
where $ b_{ij} = i \cdot j $?

📝 To recap, `ndarray` is the official name of the data type provided by NumPy, and `array` is both
the informal name of this data type and the function that we can use to create ndarrays.

A $ 3D$ array is to a matrix as a solid block is to a rectangle. In other words,
a rank $ 3 $ array is one having three axes, instead of just two. There is no
bound on the number of dimensions that an array can have, although for most
applications arrays of dimension greater than $ 3 $ are rarely used. 

__Exercise:__ Build a three-dimensional array of shape $ (2, 3, 2) $. _Hint:_ You will need triple opening brackets to start. It may help to think of the array as having $ 2 $ rows whose elements are $ 3 \times 2 $ matrices.

Besides arrays, other features provided by NumPy include (but are not limited to):
* Operations with, functions on and manipulation of arrays
* Fourier transforms and signal processing
* Basic statistical operations
* Random number generation
* Integration with various databases and file formats for data import/export

In summary, NumPy provides a high-performance multidimensional array object,
along with tools for working with these arrays. As we will see, arrays
are far more efficient and convenient for numerical computation than Python's
built-in data types, such as lists. NumPy is widely used in data analysis,
machine learning, engineering, and other fields that require intensive numerical
computation. It also serves as the basis for higher-level scientific computing
libraries such as SciPy, Pandas, and scikit-learn, cementing its role as a core
component of the Python ecosystem.